repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.1.0  # Updated to the latest version
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: v6.1.0  # Updated to the latest version
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.2  # Updated to the latest version
    hooks:
    -   id: mypy
